// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: messages.proto
#ifndef GRPC_messages_2eproto__INCLUDED
#define GRPC_messages_2eproto__INCLUDED

#include "messages.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace protowire {

class P2P final {
 public:
  static constexpr char const* service_full_name() {
    return "protowire.P2P";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> MessageStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(MessageStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> AsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(AsyncMessageStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> PrepareAsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(PrepareAsyncMessageStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void MessageStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protowire::KaspadMessage,::protowire::KaspadMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* AsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* PrepareAsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> MessageStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(MessageStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> AsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(AsyncMessageStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> PrepareAsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(PrepareAsyncMessageStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MessageStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protowire::KaspadMessage,::protowire::KaspadMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* AsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* PrepareAsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MessageStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MessageStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MessageStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMessageStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MessageStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MessageStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::protowire::KaspadMessage, ::protowire::KaspadMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MessageStream(context); }));
    }
    ~WithCallbackMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_MessageStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MessageStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MessageStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMessageStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MessageStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MessageStream(context); }));
    }
    ~WithRawCallbackMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* MessageStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

class RPC final {
 public:
  static constexpr char const* service_full_name() {
    return "protowire.RPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> MessageStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(MessageStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> AsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(AsyncMessageStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> PrepareAsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(PrepareAsyncMessageStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void MessageStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protowire::KaspadMessage,::protowire::KaspadMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* AsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* PrepareAsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> MessageStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(MessageStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> AsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(AsyncMessageStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>> PrepareAsyncMessageStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>>(PrepareAsyncMessageStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MessageStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protowire::KaspadMessage,::protowire::KaspadMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* AsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* PrepareAsyncMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MessageStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MessageStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MessageStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMessageStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MessageStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MessageStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::protowire::KaspadMessage, ::protowire::KaspadMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MessageStream(context); }));
    }
    ~WithCallbackMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* MessageStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_MessageStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MessageStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MessageStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMessageStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MessageStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MessageStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MessageStream(context); }));
    }
    ~WithRawCallbackMethod_MessageStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MessageStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protowire::KaspadMessage, ::protowire::KaspadMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* MessageStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace protowire


#endif  // GRPC_messages_2eproto__INCLUDED
